import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/context/theme-provider";
import { ChatProvider } from "@/context/chat-provider";
import { AuthProvider } from "@/context/auth-provider";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ChatBot UI",
  description: "Generated by create next app",
  icons: {
    icon: "/arinovalogo.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider><AuthProvider>
          <ThemeProvider>
            <ChatProvider>
              <div className="flex h-screen">
                <main className="flex-1 overflow-auto">
                  {children}
                </main>
              </div>
            </ChatProvider>
          </ThemeProvider>
        </AuthProvider></SessionProvider>
      </body>
    </html>
  );
}
